# Site settings
title: Test test test
header-img: img/home-bg.jpg
email: genevieve_ngo@yahoo.com
copyright_name: Genevieve Ngo
description: "A test website, for now :)"
baseurl: "https://genevievengo.github.io"
url: "https://genevievengo.github.io"
#twitter_username: 
github_username:  genevievengo
facebook_username:  genevievecngo
email_username:  genevieve_ngo@yahoo.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
